version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /assets
  static_dir: templates/assets

- url: /.*
  script: LandingPage.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

application: maeklandingpage
